package com.github.retro_game.retro_game.entity;

public enum AlliancePrivilege {
  SHOW_APPLICATIONS,
  PROCESS_APPLICATIONS,
  SHOW_MEMBER_LIST,
  KICK_USER,
  SEE_ONLINE_STATUS,
  WRITE_CIRCULAR_MESSAGE,
  DISBAND_ALLIANCE,
  MANAGE_ALLIANCE,
  RIGHT_HAND,
}
