package com.github.retro_game.retro_game.dto;

public enum BuildingKindDto {
  METAL_MINE,
  CRYSTAL_MINE,
  DEUTERIUM_SYNTHESIZER,
  SOLAR_PLANT,
  FUSION_REACTOR,
  ROBOTICS_FACTORY,
  NANITE_FACTORY,
  SHIPYARD,
  METAL_STORAGE,
  CRYSTAL_STORAGE,
  DEUTERIUM_TANK,
  RESEARCH_LAB,
  TERRAFORMER,
  ALLIANCE_DEPOT,
  LUNAR_BASE,
  SENSOR_PHALANX,
  JUMP_GATE,
  MISSILE_SILO,
}
