package com.github.retro_game.retro_game.dto;

public enum BuildingQueueErrorDto {
  BUILDING_ALREADY_DESTROYED,
  CANNOT_CANCEL,
  CANNOT_MOVE,
  MISSING_EVENT,
  NOT_ENOUGH_ENERGY,
  NOT_ENOUGH_RESOURCES,
  NO_MORE_FREE_FIELDS,
  NO_SUCH_QUEUE_ENTRY,
  QUEUE_FULL,
  REQUIREMENTS_NOT_MET,
  WRONG_BUILDING_KIND,

  CONCURRENCY,
}
