package com.github.retro_game.retro_game.dto;

public enum ShipyardQueueErrorDto {
  REQUIREMENTS_NOT_MET,
  NOT_ENOUGH_RESOURCES,
  TOO_MANY_SHIELD_DOMES,
  SHIELD_DOME_ALREADY_BUILT,
  SHIELD_DOME_ALREADY_IN_QUEUE,
  NOT_ENOUGH_CAPACITY,

  CONCURRENCY,
}
