package com.github.retro_game.retro_game.model.entity;

public enum TechnologyKind {
  ESPIONAGE_TECHNOLOGY,
  COMPUTER_TECHNOLOGY,
  WEAPONS_TECHNOLOGY,
  SHIELDING_TECHNOLOGY,
  ARMOR_TECHNOLOGY,
  ENERGY_TECHNOLOGY,
  HYPERSPACE_TECHNOLOGY,
  COMBUSTION_DRIVE,
  IMPULSE_DRIVE,
  HYPERSPACE_DRIVE,
  LASER_TECHNOLOGY,
  ION_TECHNOLOGY,
  PLASMA_TECHNOLOGY,
  INTERGALACTIC_RESEARCH_NETWORK,
  ASTROPHYSICS,
  GRAVITON_TECHNOLOGY,
}
