package com.github.retro_game.retro_game.service.dto;

public enum UnitKindDto {
  SMALL_CARGO,
  LARGE_CARGO,
  LITTLE_FIGHTER,
  HEAVY_FIGHTER,
  CRUISER,
  BATTLESHIP,
  COLONY_SHIP,
  RECYCLER,
  ESPIONAGE_PROBE,
  BOMBER,
  SOLAR_SATELLITE,
  DESTROYER,
  DEATH_STAR,

  ROCKET_LAUNCHER,
  LIGHT_LASER,
  HEAVY_LASER,
  GAIUS_CANNON,
  ION_CANNON,
  PLASMA_TURRET,
  SMALL_SHIELD_DOME,
  LARGE_SHIELD_DOME,
  ANTI_BALLISTIC_MISSILE,
  INTERPLANETARY_MISSILE,
}
